### PR TITLE
Migrated to terraform-plugin-sdk/v2

### LINKED ISSUE #586: Migration to terraform-plugin-sdk/v2
I left the template headers but it does not fit with them.

Basically Terraform released a while back the v2 of the sdk https://github.com/hashicorp/terraform-plugin-sdk and I was wondering if this Provider was intending to migrate to it.

I'll work on a PR for it as I need it for a project I'm working on. I'll open the PR to this repo too just in case it's wanted. Sometimes this changes are big and require some more internal testing that's why I'm asking beforehand too hehe.

### PR DESCRIPTION
**Pull request by xescugc**
I was not able to test 100% all the changes, now all of them are compiling with the new format but I get the following error:

```
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
go test: -i flag is deprecated
echo $(go list ./... |grep -v 'vendor') | \
        xargs -t -n4 go test  -timeout=30s -parallel=4
go test '-timeout=30s' '-parallel=4' github.com/terraform-providers/terraform-provider-flexibleengine github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine
?       github.com/terraform-providers/terraform-provider-flexibleengine        [no test files]
panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag": *tfdiags.rpcFriendlyDiag != *tfdiags.rpcFriendlyDiag

goroutine 1 [running]:
encoding/gob.RegisterName(0x1405d6c, 0x18, 0x15589a0, 0x0)
        /usr/lib/go/src/encoding/gob/type.go:820 +0x567
encoding/gob.Register(0x15589a0, 0x0)
        /usr/lib/go/src/encoding/gob/type.go:874 +0x12c
github.com/hashicorp/terraform-plugin-sdk/internal/tfdiags.init.0()
        /home/xescugc/go/src/github.com/xescugc/terraform-provider-flexibleengine/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfdiags/rpc_friendly.go:58 +0x36
FAIL    github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 0.013s
FAIL
make: *** [GNUmakefile:13: test] Error 123
```
which is this issue https://github.com/hashicorp/terraform-plugin-sdk/issues/268 and IDK what is actually triggering it. I did face this issue on the poast when I had Terraform and the SDK beeing imported in a single repository, but this is not the case.

Do you have any idea what could be causing it?

Closes #586

### CODE REVIEW

**Comment by xescugc** [comment]
OK the CI failed for the same error, I'm quite clueless on why is it being triggered here ... mmm.

**Comment by ShiChangkuo** [comment]
@xescugc Thanks for your effort, I will check it as possible as I can.

**Comment by xescugc** [comment]
Ok found the error, I was "guessing" it was for that but I was not sure if it happen also on that usecase.

The issue is that this repo is importing `"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"` which is on [`terraform-plugin-sdk/v1`](https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/go.mod#L8) and the panic happens because they register to the same "type" but as thery are 2 different packages then it fails, this also happens if you import Terraform and the terraform-plugin-sdk (which is what I faced on the past).

Possible solutions:
* Update the `terraform-provider-huaweicloud` to v2 too.
* Remove the import to that package.

I would recommend the 2nd one as Terraform itself (form the [documentation](https://www.terraform.io/docs/extend/best-practices/depending-on-providers.html#do-not-import-providers-as-go-modules)) do not recommend for anyone to import other providers directly.

I'm gonna investigate how easy is to remove it for now, but I let you @ShiChangkuo decide on which solution to take as IDK which approach is better in terms of product.

**Comment by ShiChangkuo** [comment]
@xescugc you are right. When I modify `github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config` to make it do not import `terraform-plugin-sdk/v1` package locally, the test goes well.

we use the `huaweicloud/config` package to obtain the endpoint of services conveniently, so I want to keep the package and update it to `terraform-plugin-sdk/v2`. Actually, we have opened an issue in huaweicloud/terraform-provider-huaweicloud#1265.

**Comment by xescugc** [comment]
Well then I guess I'll take https://github.com/huaweicloud/terraform-provider-huaweicloud/issues/1265 hahahaha

**Comment by ShiChangkuo** [comment]
I will implement it before August 10th.

**Comment by xescugc** [comment]
I would really like to have it "shortly" so if you don't mind I can take the https://github.com/huaweicloud/terraform-provider-huaweicloud/issues/1265 and have a PR open for next week.

If you agree OFC :)

**Comment by xescugc** [comment]
Ok I went ahead (sorry but I needed it) and migrated huaweicloud https://github.com/huaweicloud/terraform-provider-huaweicloud/pull/1309 so until that PR is merged this PR is blocked.

**Comment by ShiChangkuo** [comment]
the testing result:
```
$ make build
==> Checking that code complies with gofmt requirements...
go install

$ make testacc TEST='./flexibleengine' TESTARGS='-run TestAccComputeV2Instance_basic'  ==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./flexibleengine -v -run TestAccComputeV2Instance_basic -timeout 720m
=== RUN   TestAccComputeV2Instance_basic
--- PASS: TestAccComputeV2Instance_basic (138.56s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 138.576s

$ make testacc TEST='./flexibleengine' TESTARGS='-run=TestAccFlexibleEngineVpcSubnetV1_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./flexibleengine -v -run=TestAccFlexibleEngineVpcSubnetV1_basic -timeout 720m
=== RUN   TestAccFlexibleEngineVpcSubnetV1_basic
--- PASS: TestAccFlexibleEngineVpcSubnetV1_basic (64.12s)
PASS
ok      github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine 64.135s
```

**Pull request merged**
